FROM node:14.16.0-alpine3.13

RUN mkdir -p /src/app

WORKDIR /src/app

# copy everything into the working directory
COPY . /src/app

# install dependencies
RUN npm install

EXPOSE 3001

CMD ["npm", "start"]